### ISSUE TITLE
Latest version not in Ansible Galaxy

### ISSUE THREAD

**Issue by LisaHelm** [AlbanAndrieu/ansible-jmeter#5]
Hi,

I'd really like to be use this through ansible galaxy, but I've noticed that it doesn't have the current version of the master branch. Any chance you would be able to put it up?

Thanks!

**Comment by AlbanAndrieu** [comment]
On galaxy https://galaxy.ansible.com/alban.andrieu/jmeter/
You should be able to install it doing ansible-galaxy install alban.andrieu.jmeter
