### ISSUE TITLE
Ansible 2.0 support requires changes to meta/main.yml

### ISSUE THREAD

**Issue by HDYA** [AlbanAndrieu/ansible-jmeter#6]
similar to what's posted on https://github.com/nickjj/ansigenome/issues/33

**Comment by AlbanAndrieu** [comment]
Feel free to chase if I cannot find some time to fix it in the coming day.

If your are stuck because of that you can remove galaxy_info from meta/main.yml I will merge it straight away.

**Comment by AlbanAndrieu** [comment]
Is commit https://github.com/AlbanAndrieu/ansible-jmeter/commit/57f1e113a4c27ddd7c21a440b759f928b23bd3de enough for you?
